; Papan ESP32-WROOM-32. Relay onboard tidak ditambah dari luar.
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps = bblanchon/ArduinoJson@^7.4.2
